services:
  coturn:
    image: instrumentisto/coturn
    container_name: coturn
    restart: always
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "5349:5349"
      - "5349:5349/udp"
      - "49160-49200:49160-49200/udp"
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf
    environment:
      - TZ=Asia/Tehran
